# Generated by Django 5.1.4 on 2025-01-29 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'User Account', 'verbose_name_plural': 'User Accounts'},
        ),
    ]
