# Generated by Django 5.1.4 on 2025-02-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_orderitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cost',
            field=models.DecimalField(decimal_places=5, default=1, max_digits=20),
            preserve_default=False,
        ),
    ]
